version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    
    environment:
      PG_PASSWORD: postgres
      PG_USER: postgres
      PG_HOST: db
      PG_DB: postgres
      PORT: 4000
      SECRET: asdfasdfasdfkasjhdfwe87934ujkjasdjfas
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
      ADMIN_USERNAME: bourdain
      ADMIN_PASSWORD: bourdain
      ENVIRONMENT: dev
      DB: firestore

      
    entrypoint: ["/bin/sh", "/usr/src/app/docker-entrypoint.sh"]
    command: ["node", "start.js"]
      
    ports:
      - 4000:4000

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    
    environment:
      NEXT_PUBLIC_API_HOST: localhost
      NEXT_PUBLIC_API_PORT: 4000
      NEXT_PUBLIC_API_PREFIX: http
      
    ports:
      - 3000:3000

  frontend-admin:
    build: 
      context: ./frontend-admin
      dockerfile: Dockerfile
    
    environment:
      NEXT_PUBLIC_API_HOST: localhost
      NEXT_PUBLIC_API_PORT: 4000
      NEXT_PUBLIC_API_PREFIX: http
      
    ports:
      - 5000:3000

  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

    ports:
      - 5432:5432

volumes:
  postgres-data:
